name: SIO221A
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh==2.2.1
  - datashader==0.11.1
  - holoviews==1.13.4
  - hvplot==0.4.0
  - libnetcdf==4.6.1
  - matplotlib==3.2.2
  - nc-time-axis==1.2.0
  - netcdf4==1.4.2
  - numpy==1.19.1
  - pandas==1.1.3
  - xarray==0.16.1
  - scipy==1.5.2
  - jupyterlab==2.2.6
